SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS A
JOIN SKILLCODES B
ON A.SKILL_CODE & B.CODE > 0
WHERE B.CATEGORY = 'Front End'
GROUP BY A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
ORDER BY A.ID;
