-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT DISTINCT F.FLAVOR, F.TOTAL_ORDER
    FROM FIRST_HALF F INNER JOIN ICECREAM_INFO I
    ON (F.FLAVOR = I.FLAVOR)
    WHERE F.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
    ORDER BY F.TOTAL_ORDER DESC
)
GROUP BY FLAVOR;