SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE 1=1
AND P.DURATION_TYPE = '30일 이상'
AND C.CAR_TYPE IN ('세단', 'SUV')
AND NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE 1=1
    AND C.CAR_ID = H.CAR_ID
    AND TO_CHAR(H.START_DATE, 'YYYYMMDD') <= '20221130'
    AND TO_CHAR(H.END_DATE, 'YYYYMMDD') >= '20221101'
)
AND FLOOR(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2, 1 DESC