-- 코드를 작성해주세요
SELECT EXTRACT(YEAR FROM E.DIFFERENTIATION_DATE) AS YEAR,
S.MAX_VALUE - E.SIZE_OF_COLONY AS YEAR_DEV,
E.ID
FROM (
    SELECT EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_VALUE
    FROM ECOLI_DATA
    GROUP BY YEAR
) S, ECOLI_DATA E
WHERE 1=1
AND EXTRACT(YEAR FROM E.DIFFERENTIATION_DATE) = S.YEAR
ORDER BY 1, 2