SELECT A.CATEGORY, SUM(B.TOTAL) AS TOTAL_SALES
FROM BOOK A
INNER JOIN (
    SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS TOTAL
    FROM BOOK_SALES
    WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'
    GROUP BY BOOK_ID, SALES_DATE, SALES
) B
ON A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY 1