-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_REPLY R
ON B.BOARD_ID = R.BOARD_ID
WHERE 1=1
AND EXTRACT(YEAR FROM B.CREATED_DATE) = 2022
AND EXTRACT(MONTH FROM B.CREATED_DATE) = 10
ORDER BY 6, 1