-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, A.PRICE * B.SALES_AMOUNT AS SALES
FROM PRODUCT A
INNER JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 2 DESC, 1

-- 코드를 입력하세요
-- SELECT A.PRODUCT_CODE, A.PRICE * SUM(B.PRODUCT_ID) AS SALES
-- FROM PRODUCT A
-- INNER JOIN OFFLINE_SALE B
-- ON A.PRODUCT_ID = B.PRODUCT_ID
-- GROUP BY A.PRODUCT_CODE, A.PRICE
-- ORDER BY 2 DESC, 1