-- 코드를 입력하세요
SELECT A.MEMBER_NAME, C.REVIEW_TEXT, TO_CHAR(C.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE A
INNER JOIN (
    SELECT MEMBER_ID, COUNT(*)
    FROM REST_REVIEW
    WHERE MEMBER_ID IS NOT NULL
    GROUP BY MEMBER_ID
    ORDER BY 2 DESC
    FETCH FIRST 1 ROW ONLY
) B
ON A.MEMBER_ID = B.MEMBER_ID,
REST_REVIEW C
WHERE A.MEMBER_ID = B.MEMBER_ID
AND B.MEMBER_ID = C.MEMBER_ID
ORDER BY 3, 2