-- 코드를 작성해주세요
SELECT F.ID, S.FISH_NAME, S.LENGTH
FROM (
    SELECT F.FISH_TYPE, N.FISH_NAME, MAX(F.LENGTH) AS LENGTH
    FROM FISH_INFO F INNER JOIN FISH_NAME_INFO N
    ON F.FISH_TYPE = N.FISH_TYPE
    GROUP BY F.FISH_TYPE, N.FISH_NAME
    ORDER BY 3 DESC
) S, FISH_INFO F
WHERE 1=1
AND F.FISH_TYPE = S.FISH_TYPE
AND F.LENGTH = S.LENGTH
ORDER BY F.ID