name: Update CSV

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.yml'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python 3.10 
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython

    - name: Run Python scripts
      run: |
        python README.py changed

    - name: Check for README changes
      run: |
        git config --global user.name 'zzzz955'
        git config --global user.email 'zzzzz955@gmail.com'
        # md 파일만 스테이징
        if ls README.md 1> /dev/null 2>&1; then
          git add README.md
        fi
        # 스테이징된 변경사항이 있는지 확인
        if [[ -n $(git diff --staged) ]]; then
          git commit -m "Update README.md file"
          git push
        else
          echo "No changes in README.md files"
        fi
